OK-42159 dev, stage 환경 github action 파일 작성
bucketplace/contents.ohou.se pull request #3
Opened 2022-05-18 07:11 UTC by bucketressi

배포 파일(.yaml) + Dockerfile 작성하였습니다.

[슬랙](https://ohou-se.slack.com/archives/C02D1E0778X/p1652856209452309)을 통해 배포 환경 부탁드렸고,
완료 되면 해당 PR까지 검토 받고 올리려고 합니다.

- dev : contents.dev.dailyhou.se (main 배포 전에 확인 용도)
- stage : contents.stage-web.dailyhou.se (검증 용도)

더해서 추후에 prod 배포 환경 지원 요청 드리면서는 이전에 @bread-kwon 님께서 제안 주셨듯이 tag 따면 배포되는 방식으로 해볼까 합니다!

2022-05-18 07:24 UTC, suminhong commented on .env.dev
> +HOSTNAME=contents.dev.dailyhou.se
렛시님! 요기 `contents.dev-web.dailyhou.se` 아닌가요 ?.?

2022-05-18 07:45 UTC, bucketressi commented on .env.dev
> +HOSTNAME=contents.dev.dailyhou.se
꺅 그러네요 수정하겠습니다!

2022-05-18 07:55 UTC, suminhong requested changes
렛시님~ DEV 환경은 AWS KEY 이름이 달라서 수정 제안 했습니다!!
그리고 branch 네임들도 맞는지 확인 부탁드려요 ~.~

2022-05-18 07:55 UTC, suminhong commented on .github/workflows/deploy-to-dev.yaml
> +          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
```suggestion
          access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
```

2022-05-18 07:55 UTC, suminhong commented on .github/workflows/deploy-to-dev.yaml
> +          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```suggestion
          secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
```

2022-05-18 07:55 UTC, suminhong commented on .github/workflows/deploy-to-dev.yaml
> +    needs: [get-image-tag, publish-assets]
publish-assets 이 없어서 에러날 것 같아요..! `build-and-push` 아니실까요?

2022-05-18 07:55 UTC, suminhong commented on .github/workflows/deploy-to-dev.yaml
> +          account_id: "${{ secrets.AWS_ACCOUNT_ID }}"
```suggestion
          account_id: "${{ secrets.DEV_AWS_ACCOUNT_ID }}"
```

2022-05-18 08:48 UTC, zezaeoh approved these changes
감사합니다! 👍

2022-05-18 08:48 UTC, zezaeoh commented on .github/workflows/deploy-to-dev.yaml
> +name: Deploy to Prod K8S
```suggestion
name: Deploy to Dev K8S
```

2022-05-18 10:11 UTC, bread-kwon commented
@bucketressi 
아래대로 의도하신거죠?
```
main merge 시 dev 배포
develop merge 시 stage 배포
```

2022-05-19 01:55 UTC, bucketressi commented on .github/workflows/deploy-to-dev.yaml
> +          account_id: "${{ secrets.AWS_ACCOUNT_ID }}"
dev 는 따로 설정해주어야 하는군요..! 홍랩님 감사합니다 :)

2022-05-19 02:08 UTC, merged